### ISSUE TITLE
Windows: FontTools installation via pip fails

### ISSUE THREAD

**Issue by midenok** [eosrei/emojione-color-font#56] opened 2016-10-03 17:27 UTC
```
C:\home\soft\fonts\emoji\EmojiOneColor-SVGinOT-Win-1.3>install.cmd
Checking if Segoe UI Emoji is installed
Checking if Segoe UI Symbol is installed.
Checking if prerequisites are installed.
Ensuring the latest FontTools is installed.
Collecting https://github.com/behdad/fonttools/archive/master.zip
  Downloading https://github.com/behdad/fonttools/archive/master.zip (691kB)
    100% |################################| 696kB 819kB/s
    Complete output from command python setup.py egg_info:

    Installed c:\users\op\appdata\local\temp\pip-9s_omy-build\.eggs\setuptools_scm-1.11.1-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\op\appdata\local\temp\pip-9s_omy-build\setup.py", line 79, in <module>
        **classifiers
      File "c:\program files\python27\lib\distutils\core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\program files\python27\lib\site-packages\setuptools\dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "c:\program files\python27\lib\distutils\dist.py", line 287, in __init__
        self.finalize_options()
      File "c:\program files\python27\lib\site-packages\setuptools\dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "build\bdist.win-amd64\egg\setuptools_scm\integration.py", line 19, in version_keyword
      File "build\bdist.win-amd64\egg\setuptools_scm\__init__.py", line 104, in get_version
      File "build\bdist.win-amd64\egg\setuptools_scm\__init__.py", line 82, in _do_parse
    LookupError: setuptools-scm was unable to detect version for 'c:\\users\\op\\appdata\\local\\temp\\pip-9s_omy-build'.

    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the
 .git folder) don't contain the necessary metadata and will not work.

    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\op\appdata\local\temp\pip-9s_omy-build\

ttx.exe not found, please add Python's Scripts folder to PATH

Installation failed!
Press any key to continue . . .
```

**Comment by 13rac1** [comment] 2016-10-03 17:52
Oh Windows.... Haha! What an amazing error you've discovered!

First thing, this is designed and tested with Python3. According to the above error, you are using Python2. Please install Python3 and follow these directions: https://github.com/eosrei/emojione-color-font#replace-the-default-windows-emoji-fonts

**Comment by midenok** [comment] 2016-10-04 02:41
On Python 3 it produces similar stack trace (tried it first).

**Comment by 13rac1** [comment] 2016-10-04 06:48
Can you try manually fonttools via pip using this command from #55?

```
pip install --upgrade git+https://github.com/behdad/fonttools.git#egg=fonttools
```

This is what the error message says to do.

**Comment by heyitsols** [comment] 2016-10-07 08:09
Whew, had a fun 20 minutes sorting this out!

I started with python3 and was getting the same error

```
ttx.exe not found, please add Python's Scripts folder to PATH
```

~~First problem, ttx isn't installed by default, so grab that from here _(Link removed by @eosrei)_ **trigger warning: sourceforge**, install it and throw it in your PATH if it isn't already. I'm dirty so just copied the .exe to the %appdata%\Local\Programs\Python35\Scripts folder~~

```
The program can't start because python22.dll is missing from your computer.
```

~~Second problem, ttx (or at least the version I downloaded) requires python22.dll, so I installed python2.2.2 (2.7 didn't seem to provide this) from [here](https://www.python.org/ftp/python/2.2.2/Python-2.2.2.exe)~~

```
The requested file <path>\Segoe UI Symbol with EmojiOne.ttf is not a valid font file
```

~~Third problem, the install script is looking to a file that doesn't exist. The file is actually called `EmojiOneColor-SVGinOT.ttf`. I just renamed the file rather than changing the script, but should be an easy fix~~

Looking again I think it's just failing to create the font file, but the script doesn't exit with an error, it still says that the font has been created because it's missing another library:

```
IOError: [Errno 2] No such file or directory: 'C:\\Users\\muggahtee\\AppData\\Local\\Programs\\Python\\Python35\\Scripts\\_sre.pyd'
Could Not Find C:\Users\muggahtee\AppData\Local\Temp\almost.ttf
Could Not Find C:\Users\muggahtee\AppData\Local\Temp\svg.ttx
```

Each function has a traceback similar, unable to find the previously created files

**Comment by midenok** [comment] 2016-10-07 08:33
> Can you try manually fonttools via pip using this command from #55?

```
C:\home\soft\fonts\emoji\EmojiOneColor-SVGinOT-Win-1.3>pip install --upgrade git+https://github.com/behdad/fonttools.git#egg=fonttools
Collecting fonttools from git+https://github.com/behdad/fonttools.git#egg=fonttools
  Cloning https://github.com/behdad/fonttools.git to c:\users\op\appdata\local\temp\pip-build-b9gkj9o8\fonttools
    Complete output from command python setup.py egg_info:

    Installed c:\users\op\appdata\local\temp\pip-build-b9gkj9o8\fonttools\.eggs\setuptools_scm-1.13.0-py3.6.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\op\AppData\Local\Temp\pip-build-b9gkj9o8\fonttools\setup.py", line 79, in <module>
        **classifiers
      File "c:\program files\python36\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\program files\python36\lib\site-packages\setuptools\dist.py", line 318, in __init__
        _Distribution.__init__(self, attrs)
      File "c:\program files\python36\lib\distutils\dist.py", line 281, in __init__
        self.finalize_options()
      File "c:\program files\python36\lib\site-packages\setuptools\dist.py", line 375, in finalize_options
        ep.load()(self, ep.name, value)
      File "c:\users\op\appdata\local\temp\pip-build-b9gkj9o8\fonttools\.eggs\setuptools_scm-1.13.0-py3.6.egg\setuptools_scm\integration.py", line 19, in version_k
eyword
      File "c:\users\op\appdata\local\temp\pip-build-b9gkj9o8\fonttools\.eggs\setuptools_scm-1.13.0-py3.6.egg\setuptools_scm\__init__.py", line 117, in get_version

      File "c:\users\op\appdata\local\temp\pip-build-b9gkj9o8\fonttools\.eggs\setuptools_scm-1.13.0-py3.6.egg\setuptools_scm\__init__.py", line 95, in _do_parse
    LookupError: setuptools-scm was unable to detect version for 'C:\\Users\\op\\AppData\\Local\\Temp\\pip-build-b9gkj9o8\\fonttools'.

    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the
 .git folder) don't contain the necessary metadata and will not work.

    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\op\AppData\Local\Temp\pip-build-b9gkj9o8\fonttools\
```

**Comment by heyitsols** [comment] 2016-10-07 09:08
Hey would you look at that! Fixed :)

Note that this worked with 2.7 on Windows 7

**Comment by midenok** [comment] 2016-10-07 09:12
Where did you see fix?

**Comment by heyitsols** [comment] 2016-10-07 14:16
@midenok I ran:

```
pip install --upgrade git+https://github.com/behdad/fonttools.git#egg=fonttools
```

**Comment by midenok** [comment] 2016-10-07 14:42
@muggahtee I don't see fix, because command fails for me.

**Comment by 13rac1** [comment] 2016-10-07 14:45
You both have separate issues.

@muggahtee Nice! I'll update the install.cmd script.

@midenok I cannot reproduce this issue. There's distinctly something wrong with your Python install or system. What version of Python3 are you running? `python3 -V`
Here is Win10:
![pip-install-ttx](https://cloud.githubusercontent.com/assets/195061/19193819/7bbff428-8c60-11e6-9fd6-283b1638f4ff.png)

**Comment by midenok** [comment] 2016-10-07 14:48
Python 3.6.0b1

**Comment by 13rac1** [comment] 2016-10-07 14:50
# Solution for the original issue

Ah I see. That's a beta. Please install the newest full release 3.5.2: https://www.python.org/downloads/release/python-352/

**Comment by 13rac1** [comment] 2016-10-07 14:50
I'll update the readme to specify full releases only.

**Comment by jbmonroe** [comment] 2016-10-11 11:18
The Real WTF, as we used to say, is that it requires Python at all.  If my 90-year-old father or mother-in-law wanted full emoji support (let's skip over why they would), they couldn't install the font because (like, oh, 99% of the people using the web), they don't have Python installed, nor would they have a reason to.  Seriously, you can't sort out an install process that doesn't service developers only?

**Comment by 13rac1** [comment] 2016-10-11 17:00
@jbmonroe Haha! This type of angry comment is _exactly_ why I was concerned about supporting Windows in the first place. 😝

>  99% of the people using the web), they don't have Python installed,

Both Linux and MacOS do. 9%+ of the web. Although, it's only the Windows install which requires Python, haha!

> Seriously, you can't sort out an install process that doesn't service developers only?

I could, but don't want to. Linux is my primary concern. The MacOS install was an easy addon. The Windows install was kindly provided by @yincrash and is a workaround for three issues:
1. Windows requires some of the characters in the provided Emoji and Symbol fonts.
2. The Windows font configuration is not complex enough to handle replacing parts of fonts or even simply re-ordering the font list.
3. I cannot redistribute the merged Windows system fonts due to the Microsoft software licensing requirements.

The only way to make this run "without Python" is to build an executable from the Python code. Next steps (perhaps _your_ next steps?): 
1. Install Ubuntu 16.04 on hardware or VM.
2. Install git and the font build requirements: https://github.com/eosrei/emojione-color-font#building
3. Download and test [PyInstaller](http://www.pyinstaller.org/).
4. Use PyInstaller in [Wine](https://www.winehq.org/) to create a Windows executable.
5. Create a new branch in the repo.
6. Automate the executable compilation process in the Makefile.
7. Automate the package build process in the Makefile.
8. Update the README.md with the new build and user instructions.
9. Build the Windows package.
10. Test on a fresh Windows 10 VM: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms
11. Commit the changes to your branch.
12. Submit a pull request.

I have no plans to do the above, but I'll merge a PR if someone does it. 😚😇😀

**Comment by moyogo** [comment] 2016-10-11 17:06
@eosrei it would be better to `pip install --upgrade fonttools` or `pip install --upgrade "fonttools>=3.1.2"`.

**Comment by 13rac1** [comment] 2016-10-11 17:11
@moyogo At the time the Windows install was created the current repo version was required since it included fresh commits by @yincrash. Is 3.1.2 the minimum version with the needed functionality?

**Comment by jbmonroe** [comment] 2016-10-11 21:10
I understand the licensing thing.  I still don't understand how the hell we
built software prior to 1989 without Python, but apparently we did it.  Or
maybe nobody believes that.

**Comment by yincrash** [comment] 2016-10-11 21:27
3.1.0 is the minimum version of fonttools required. The Windows build was made before they decided to make a new 3.1.0 release of fonttools. @muggahtee I worry that someone is going to install the old TTX again in from your comment, so a strikeout of that ~~sourceforge link~~ would be helpful. It's so super old. 

The reason Python is required is because basically all open source font development is done via Python. Should probably blame the Van Rossum brothers for that, but it actually works very well.

**Comment by 13rac1** [comment] 2016-10-11 22:08
@yincrash Good point! I've removed it.

@jbmonroe Thousands of applications run Python on all three OSs. There's no reason to use C/C++ unless you need it and we definitely don't in this case. Plus, as I've already described above, someone could make an executable for Windows users.

_I'm amazed to be justifying the use of a 25 year old programming language._ LOL

**Comment by moyogo** [comment] 2016-10-12 06:58
@jbmonroe The issue here is that the only available font merger there is is written in Python. An executable for Windows users or a font merger in something other than Python are welcomed.

@eosrei & @jbmonroe The license of Segoe UI Emoji or that of Segoe UI Symbols doesn’t allow modification either.

This is the License Description in both segoeuiemj.ttf and seguisym.ttf:

> You may use this font as permitted by the EULA for the product in which this font is included to display and print content. You may only (i) embed this font in content as permitted by the embedding restrictions included in this font; and (ii) temporarily download this font to a printer or other output device to help print content.

**Comment by jbmonroe** [comment] 2016-10-12 16:12
Licenses are fun. o,O

@brad -- As for justifying the use of a 25-year-old programming
language--after 25 years it's obsolete and we're supposed to be using, uh,
CoffeeScript in NPM for this now?  ;)

**Comment by 13rac1** [comment] 2016-10-12 22:54
@moyogo Ah yes, yet another reason I cannot distribute the fonts. I have no control of what people do on their own computers though...

@jbmonroe CoffeeScript?! No no, that's right out. ES6 is the current answer: https://www.google.com/trends/explore?q=coffeescript,es6 A font merge tool could be written in Node: https://github.com/devongovett/fontkit but it's consistent to use the same "official" Python library my color font build tool uses: https://github.com/fonttools/fonttools

**Comment by jbmonroe** [comment] 2016-10-13 17:54
All kidding aside, I wondered about doing it in Node.

**Comment by 13rac1** [comment] 2017-05-03 05:00
Solution is being tracked in #55. Has been commited to https://github.com/eosrei/twemoji-color-font/commit/e3e5da31dc1090ff8acc9ac9b02371f470f325b0

**Closed as completed by 13rac1** 2017-05-03 05:00 UTC
