### ISSUE TITLE
Squirrel glyph color inversion

### ISSUE THREAD

**Issue by Happy-Ferret** [eosrei/emojione-color-font#21] opened 2016-03-17 16:12 UTC
Just a minor issue, but when I mark the squirrel/chipmunk glyph ( 🐿 ) , the black in its eye and along the tail are inverted to white. 

This particular glyph seems to be quite unique in this way, as I cannot reproduce it with any of the other glyphs I've screened, so far.

Tested under Windows 8.1, with Firefox 45.

**Comment by 13rac1** [comment] 2016-03-17 18:34
Thanks for reporting.

Interesting. I use SVGs from the Emoji One project as-is. I can reproduce it and narrowed it down to missing SVG fills on three of the paths in that file. It seems Firefox does the "regular" selected text color inversion only when the path fill is not set.

This is an issue with the Emoji One project: https://github.com/Ranks/emojione/blob/master/assets/svg/1f43f.svg

When those SVGs are updated I'll change it.

**Comment by 13rac1** [comment] 2016-03-27 02:41
@Happy-Ferret Ranks Inc. has declined to accept graphic updates for the Emoji One project. I'm re-opening this to fix the problem of the `#000000` black selection inversion.

The correct procedure (in case someone wants to submit a PR):
1. Move the original squirrel to `assets/emojione-svg/disabled`
2. Copy to: `assets/svg`
3. Fix the problem by adding the correct `#3e4347` color, since it's what is used instead of black  throughout the Emoji One project, to all three paths.
4. Submit the PR. Close this issue and reference the emojione issue in the git commit message.

**Comment by 13rac1** [comment] 2016-03-28 01:46
Please close issues via PR. Details: https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by 13rac1** [comment] 2016-03-28 03:08
Screenshot of the problem for future reference:

![squirrel_before](https://cloud.githubusercontent.com/assets/195061/14070147/a3b0404c-f457-11e5-870e-fcacf3a84dba.png)

**Comment by 13rac1** [comment] 2016-03-28 03:12
After #26:
![squirrel_after](https://cloud.githubusercontent.com/assets/195061/14070189/312c141e-f458-11e5-86f2-d1c2470fb61e.png)

**Closed as completed** 2016-03-28 03:13 UTC
Labels: enhancement, help wanted, minor
