### ISSUE TITLE
[Linux] Squares instead of text in some applications

### ISSUE THREAD

**Issue by gentakojima** [eosrei/emojione-color-font#23] opened 2016-03-21 09:02 UTC
First of all, thank you _very much_ for your work. I think it's awesome to be able to see color emojis at last on Linux.

I'm having a problem with Mysql Workbench, showing squares instead of text in the main screen. Most screens and dialogs also have this problem but in a minor scale, they are mostly usable.

![mysql_workbench_63](https://cloud.githubusercontent.com/assets/2670279/13913878/eaa019c6-ef4a-11e5-8989-54713b062754.png)

Some details blurred on purpose, but not squares in there:

![mysql_workbench_63_b](https://cloud.githubusercontent.com/assets/2670279/13913996/df9e17f2-ef4b-11e5-97b3-46642188da36.png)

**Comment by 13rac1** [comment] 2016-03-21 16:06
Hi! Are you running v1.0-beta2 or v1.0-beta3? The installation procedure has completely changed due to all of these programs incorrectly using the font fallback system. 

Unless you are using v1.0-beta3, this is a duplicate of #5 and #18 which was fixed by #2 and #17.

**Comment by gentakojima** [comment] 2016-03-21 17:26
Oops. Yes, you're right. I'm running v1.0-beta2 and this seems to be fixed in v1.0-beta3, indeed.

But beta3 broke the emojis for me on Ubuntu 14.04 (already installed it before, the console is there just for demonstration purposes).

![captura de pantalla de 2016-03-21 18-24-17](https://cloud.githubusercontent.com/assets/2670279/13927511/427a4e5e-ef92-11e5-81ad-63433efa5df2.png)

**Comment by 13rac1** [comment] 2016-03-21 18:07
Well, that's why it's a beta, so I can break things! Haha!

I'm so sick of fighting fontconfig. I had no idea I'd spend so much time on it. Can you give me your output for:

``` sh
$ fc-match -s sans | head -n 10
Vera.ttf: "Bitstream Vera Sans" "Roman"
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSans-Bold.ttf: "DejaVu Sans" "Bold"
DejaVuSans-Oblique.ttf: "DejaVu Sans" "Oblique"
DejaVuSans-BoldOblique.ttf: "DejaVu Sans" "Bold Oblique"
n019003l.pfb: "Nimbus Sans L" "Regular"
Waree.ttf: "Waree" "Book"
DroidSansFallbackFull.ttf: "Droid Sans Fallback" "Regular"
KhmerOS.ttf: "Khmer OS" "Regular"
$ fc-match -s "Emoji One Color" | head -n 10
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"
Vera.ttf: "Bitstream Vera Sans" "Roman"
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSans-Bold.ttf: "DejaVu Sans" "Bold"
DejaVuSans-Oblique.ttf: "DejaVu Sans" "Oblique"
DejaVuSans-BoldOblique.ttf: "DejaVu Sans" "Bold Oblique"
n019003l.pfb: "Nimbus Sans L" "Regular"
Waree.ttf: "Waree" "Book"
DroidSansFallbackFull.ttf: "Droid Sans Fallback" "Regular"
KhmerOS.ttf: "Khmer OS" "Regular"
```

**Comment by gentakojima** [comment] 2016-03-21 18:16
Here it is. Hope you can find something odd, because from what I understand, I can't.

```
$ fc-match -s sans | head -n 10
Vera.ttf: "Bitstream Vera Sans" "Roman"
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSans-Bold.ttf: "DejaVu Sans" "Bold"
DejaVuSans-Oblique.ttf: "DejaVu Sans" "Oblique"
DejaVuSans-BoldOblique.ttf: "DejaVu Sans" "Bold Oblique"
Verdana.ttf: "Verdana" "Normal"
Arial.ttf: "Arial" "Normal"
n019003l.pfb: "Nimbus Sans L" "Regular"
Waree.ttf: "Waree" "Book"
$ fc-match -s "Emoji One Color" | head -n 10
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"
Vera.ttf: "Bitstream Vera Sans" "Roman"
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSans-Bold.ttf: "DejaVu Sans" "Bold"
DejaVuSans-Oblique.ttf: "DejaVu Sans" "Oblique"
DejaVuSans-BoldOblique.ttf: "DejaVu Sans" "Bold Oblique"
Verdana.ttf: "Verdana" "Normal"
Arial.ttf: "Arial" "Normal"
n019003l.pfb: "Nimbus Sans L" "Regular"
Waree.ttf: "Waree" "Book"

```

**Comment by 13rac1** [comment] 2016-03-21 18:20
Yes, that's correct, I know it's hidden but can you post the specific font request also:
`$ fc-match -s "Emoji One Color" | head -n 10`

I assume you've tried restarting Firefox and X(aka logoff/login)? The computer doesn't need a complete restart, just gnome/unity/etc. What about Chrome? Is it using the correct b&w glyphs?

**Comment by gentakojima** [comment] 2016-03-21 18:29
I've posted the other command also in a ninja edit some minutes ago. 

Just restarted Firefox to make sure. I can't restart X right now, but beta 2 started working right away so I didn't think of doing that. 

I'll try to restart X as soon as possible and report. Same for Chrome/Chromium, I don't use it so I'll have to install it.

**Comment by 13rac1** [comment] 2016-03-21 18:37
>  started working right away so I didn't think of doing that. 

I've noticed in some of the massive number of times I've installed the font that character updates work correctly, but complete font changes don't. I technically renamed the font between beta2 and beta3 by fixing an [oversight bug in SCFBuild](https://github.com/eosrei/scfbuild/commit/64bef36c1b6f1135b134fb579f704ee8148f084a). It was identified before as "Emoji One Color Regular", but now is correctly "Emoji One Color SVGinOT" I'm adding SVGinOT to the `fullname` to be clear about which color format is provided. I'm working on adding Apple's proprietary SBIX and the OpenType color bitmap format (Google's) to the build system too.

>  I don't use it so I'll have to install it.

You don't need to install Chrome. Just copy/paste some text into gedit or another text editor. Anything that'll use the b&w glyphs.

**Comment by gentakojima** [comment] 2016-03-21 22:07
Ok, it seems the problem only affects Firefox. Gedit looks great (in b/w of course, but at least it's using the correct emojis).

![captura de pantalla de 2016-03-21 23-05-07](https://cloud.githubusercontent.com/assets/2670279/13935781/7c313f8c-efb9-11e5-9c57-90431a4b996a.png)

Also, I've now restarted the system and the problem persists.

**Comment by gentakojima** [comment] 2016-03-21 22:39
I confirm that using the 1.0-beta3 ttf file with the fontconfig conf file from 1.0-beta2 works as expected.

After replacing new fontconfig file, it only takes a few seconds for Firefox to stop displaying emojis correctly. Putting the old fontconfig file, makes it work properly again.

I understand the new approach, but it's not working for me, for some reason. It seems like emojis from DejaVu Sans and Symbola are taking precedence.

Fun enough, I tried this on a clean 16.04 machine and it worked properly. Don't know why. I'll try it again on another user profile on the same 14.04 machine tomorrow.

**Comment by 13rac1** [comment] 2016-03-21 22:39
The problem could be a Firefox regression found by @saltyhorse: https://github.com/eosrei/emojione-color-font/issues/1#issuecomment-195918920 

It was a solution for me to "clear the firefox font cache":

> I just noticed Firefox was still using DejaVu Sans as the source for some emoji even though my new fonts.conf has it far down the list. Setting gfx.font_rendering.fontconfig.fontlist.enabled to false and restarting fixed the problem. Setting it back to true kept the new internal font list, sort of a cache clear.

Direct link to Firefox Regression: https://bugzilla.mozilla.org/show_bug.cgi?id=1254245

**Comment by gentakojima** [comment] 2016-03-21 22:51
Hey, you're right! 

Thank you for the support, I hope this gets fixed soon on Firefox. Maybe you can add a warning on the README.md to avoid annoying people like me :dancer: 

I can confirm MySQL Workbench also works properly now! :dancers:

**Comment by 13rac1** [comment] 2016-03-21 23:03
Awesome! You should/could add your specific experience to the Firefox bug report. It's caused by my font... again... haha, but your experience means far more people will encounter it.

I'll add a note about this to the readme after the GTK bug.

**Closed as completed** 2016-03-21 23:38 UTC
Labels: duplicate, question, external unmasked regression
