### ISSUE TITLE
[win10] failed to create process.

### ISSUE THREAD

**Issue by McKlatch** [eosrei/emojione-color-font#66] opened 2017-02-22 22:48 UTC
Hey there, I'm not sure what to try next, I think the problem might be to do with my directories, I use C: for my windows installation and E: for everything else.

Have checked python version (3.5) and checked directory is in PATH.

Trying to install: EmojiOneColor-SVGinOT-Win-1.3
on Windows 10

![problem](https://cloud.githubusercontent.com/assets/10469307/23234519/39d7697c-f94a-11e6-827a-6d49df12593e.jpg)

Unfortunately the script does not elaborate as to how the process failed, but it continued anyway.
after pressing "y" the warning prompt, "The requested file ... is not a valid font file" appears twice. Presumably in place of the font viewer.

![problem2](https://cloud.githubusercontent.com/assets/10469307/23236099/d8e894fa-f94f-11e6-96e5-7a28d287c650.jpg)

Fonts "C:\WINDOWS\Fonts\seguisym.ttf" and "C:\WINDOWS\Fonts\seguiemj.ttf"are not in the WINDOWS\Fonts directory before or after running script.

Consistent outcome on every use of the .cmd file included.

> Checking if Segoe UI Emoji is installed
> Checking if Segoe UI Symbol is installed.
> Checking if prerequisites are installed.
> Ensuring the latest FontTools is installed.
> Collecting https://github.com/behdad/fonttools/archive/master.zip
>   Downloading https://github.com/behdad/fonttools/archive/master.zip (832kB)
>     100% |################################| 839kB 483kB/s
> Installing collected packages: fonttools
>   Found existing installation: fonttools 3.7.3.dev0
>     Uninstalling fonttools-3.7.3.dev0:
>       Successfully uninstalled fonttools-3.7.3.dev0
>   Running setup.py install for fonttools ... done
> Successfully installed fonttools-3.7.3.dev0
> Creating new Segoe UI Emoji font from EmojiOne
> failed to create process.
> failed to create process.
> Could Not Find C:\Users\David\AppData\Local\Temp\emjname.ttx
> Creating new Segoe UI Symbol font from EmojiOne
> failed to create process.
> Dumping SVG emojis
> failed to create process.
> failed to create process.
> Merging in dumped emojis
> failed to create process.
> Could Not Find C:\Users\David\AppData\Local\Temp\merged.ttf
> Could Not Find C:\Users\David\AppData\Local\Temp\name.ttx
> failed to create process.
> Could Not Find C:\Users\David\AppData\Local\Temp\almost.ttf
> Could Not Find C:\Users\David\AppData\Local\Temp\svg.ttx
> 
> 
> The fonts are now saved in
> "E:\Users\David\Downloads\EmojiOneColor-SVGinOT-Win-1.3\Segoe UI Symbol with EmojiOne.ttf"
> and
> "E:\Users\David\Downloads\EmojiOneColor-SVGinOT-Win-1.3\Segoe UI Emoji with EmojiOne.ttf"
> After installation, the original fonts will still be located at
> "C:\WINDOWS\Fonts\seguisym.ttf"
> and
> "C:\WINDOWS\Fonts\seguiemj.ttf"
> It is not overwritten, and can be reinstalled with uninstall.cmd
> To finish installation, the font will be opened for you to install.
> 
> If the font is in a network path, copy to a local disk and
> double click to install.
> Press the [INSTALL] button in the Font Viewer, then close the viewer.
> Would you like to install the fonts now? [Y,N]?

**Comment by 13rac1** [comment] 2017-02-26 17:27
Hmm... I suggest trying the fix in #65

**Comment by 13rac1** [comment] 2017-03-01 05:38
Where do you have Python installed?

**Comment by wrobelda** [comment] 2017-03-13 16:16
The problem is caused by the fonttools package you pip-install explicitly using URL. After installation, issuing ttx command returns "failed to create process".  Simply installing fonttools with pip by using package name instead of URL (`pip install --upgrade fonttools`) fixes the problem.

**Comment by 13rac1** [comment] 2017-05-03 04:59
Solution is being tracked in #55. I've committed this in twemoji-color-font in https://github.com/eosrei/twemoji-color-font/commit/e3e5da31dc1090ff8acc9ac9b02371f470f325b0

**Closed as completed by 13rac1** 2017-05-03 04:59 UTC
