### ISSUE TITLE
Spaces around Emojione characters show up as boxes in GTK apps

### ISSUE THREAD

**Issue by IBBoard** [eosrei/emojione-color-font#7] opened 2016-03-04 21:46 UTC
If I use an Emojione supplied character in a GTK app then spaces to either side of it show up as a rectangle with four small rectangles in.

Example:
![screenshot from 2016-03-04 21-41-04](https://cloud.githubusercontent.com/assets/388582/13541046/f43ae2c8-e251-11e5-8e40-058d7ce65a94.png)

Text in the bottom is `❣   a b c ✄`. Hexdump of that is:

```
00000000  20 20 20 e2 9d a3 20 20  20 61 20 62 20 63 20 e2  |   ...   a b c .|
00000010  9c 84 20 0a                                       |.. .|
```

Firefox renders those characters fine.

Steps to reproduce:
 1) Install Emojione according to instructions in README
 2) Type "space space space" followed by an emoji (e.g. "<compose>+:+)" for a smiley face in default Gnome ibus setup)

Behaviour: Spaces suddenly turn into boxes as soon as emoji is there

Expected: Spaces stay looking like spaces!

System: Gnome 3.16, GTK 3.16, openSUSE Leap 42.1

**Comment by 13rac1** [comment] 2016-03-04 22:06
Thank you for the thorough bug report! This is a duplicate of #2. I've come up with some possible solutions and would appreciate your thoughts in that issue. Thanks!

**Closed as completed by 13rac1** 2016-03-04 22:06 UTC
Labels: bug, duplicate, external unmasked regression
